const financeTerms = [
    'Stock market Flow',
    'Investment portfolio Flow',
    'Financial statement Flow',
    'Capital gain Flow',
    'Interest rate Flow',
    'Asset management Flow',
    'Debt consolidation Flow',
    'Bond yield Flow',
    'Risk management Flow',
    'Return on investment Flow',
    'Economic growth Flow',
    'Cash flow Flow',
    'Credit score Flow',
    'Tax planning Flow',
    'Expense report Flow',
    'Liquidity ratio Flow',
    'Mortgage rate Flow',
    'Dividend income Flow',
    'Capital budgeting Flow',
    'Stock options Flow',
    'Bankruptcy protection Flow',
    'Financial advisor Flow',
    'Market capitalization Flow',
    'Real estate Flow',
    'Equity financing Flow',
    'Debt equity Flow',
    'Income tax Flow',
    'Business valuation Flow',
    'Mergers & acquisitions Flow',
    'Financial planning Flow',
    'Investment strategy Flow',
    'Net worth Flow',
    'Operating margin Flow',
    'Private equity Flow',
    'Venture capital Flow',
    'Tax liability Flow',
    'Debt financing Flow',
    'Revenue stream Flow',
    'Capital structure Flow',
    'Asset allocation Flow',
    'Cost basis Flow',
    'Retirement savings Flow',
    'Economic indicators Flow',
    'Trading volume Flow',
    'Money market Flow',
    'Fixed income Flow',
    'Asset class Flow',
    'Financial leverage Flow',
    'Risk tolerance Flow',
    'Interest expense Flow',
    'Price earnings ratio Flow',
    'Market trends Flow',
    'Operating income Flow'
];

export default financeTerms;
